### ISSUE TITLE
Need service to delete user.

### ISSUE THREAD

**Issue by Justin-Palmer** [hungernotimpossible/hni#40]
Need service to delete user or to mark the user as deleted (whichever is preferred).

**Comment by jeff3parker** [comment]
its not as easy as that because a user can belong to multiple organizations.  Removing from one organization doesn't automatically imply that we can delete the user object.  There are 2 services you can use for this:

/users/{id}/organizations/{org-id}  # remove the user from the org
/users/{id}/organizations/{org-id}/roles/{role-id} # remove the user/role from the org

**Comment by Justin-Palmer** [comment]
Hmm I see what your saying, however what about when we want to remove a volunteer from the system who is a member of every organization? I would have to loop over every organization there is and make a separate service call for each one.

Also what if I wanted to remove a client from the system so that they wouldn't have access to the text messaging system. Would removing from the organization that they exist in so that they do not exist in any organization accomplish that?
